In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('new_data.csv', sep=';')

In [3]:
data.head()

transactionId  step    amount  oldbalanceOrg  newbalanceOrig  \
0              0     1   9839.64       170136.0        160296.0   
1              1     1   1864.28        21249.0         19384.7   
2              2     1    181.00          181.0             0.0   
3              3     1    181.00          181.0             0.0   
4              4     1  11668.10        41554.0         29885.9   

   oldbalanceDest  newbalanceDest  isFraud  CASH_IN  CASH_OUT  DEBIT  PAYMENT  \
0             0.0             0.0        0      0.0       0.0    0.0      1.0   
1             0.0             0.0        0      0.0       0.0    0.0      1.0   
2             0.0             0.0        1      0.0       0.0    0.0      0.0   
3         21182.0             0.0        1      0.0       1.0    0.0      0.0   
4             0.0             0.0        0      0.0       0.0    0.0      1.0   

   TRANSFER  
0       0.0  
1       0.0  
2       1.0  
3       0.0  
4       0.0

In [4]:
X = data.drop("isFraud", axis=1)
y = data["isFraud"]

In [9]:
y.value_counts()

isFraud
0    1000000
1       8213
Name: count, dtype: int64

In [7]:
from imblearn.under_sampling import NearMiss

In [10]:
sampli = NearMiss()
X_res, y_res = sampli.fit_resample(X,y)

In [11]:
y_res.value_counts()

isFraud
0    8213
1    8213
Name: count, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, random_state=0, test_size=0.2)

In [22]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score, learning_curve
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [28]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [34]:
def best(model):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f"trin score :{model.score(X_train, y_train)}")
    print(f"test score :{model.score(X_test, y_test)}")
    print(cross_val_score(model, X_train, y_train, cv=5))
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))

    # N, train_score, val_score = learning_curve(model, X_train, y_train, cv=5, train_sizes=np.linspace(0.1,1,10))
    # plt.figure(figsize=(20,12))
    # plt.plot(N, train_score.mean(axis=1), label="train score")
    # plt.plot(N, val_score.mean(axis=1), label="val score")
    # plt.legend()
    

In [35]:
model = make_pipeline(StandardScaler(), SVC(random_state=0))

In [36]:
best(model)

trin score :0.9984779299847792
test score :0.9987827145465612
[0.99885845 0.99847793 0.99809741 0.99847793 0.99847793]
[[1626    4]
 [   0 1656]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1630
           1       1.00      1.00      1.00      1656

    accuracy                           1.00      3286
   macro avg       1.00      1.00      1.00      3286
weighted avg       1.00      1.00      1.00      3286



In [37]:
model1 = make_pipeline(StandardScaler(), RandomForestClassifier(random_state=0))

In [38]:
best(model1)

trin score :1.0
test score :0.9993913572732805
[1.         0.99923896 0.99885845 0.99923896 0.99847793]
[[1628    2]
 [   0 1656]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1630
           1       1.00      1.00      1.00      1656

    accuracy                           1.00      3286
   macro avg       1.00      1.00      1.00      3286
weighted avg       1.00      1.00      1.00      3286

